// <auto-generated />
using System;
using EWasteManagement.API.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EWasteManagement.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260919132844_AddComponentD_CommercialPlans")]
    partial class AddComponentD_CommercialPlans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EWasteManagement.API.Features.Auth.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("CK_users_role", "role IN ('household','corporate','collector','staff','admin')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.ApprovalAction", b =>
                {
                    b.Property<Guid>("ApprovalActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("approval_action_id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("action_type");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comments");

                    b.Property<Guid>("CommercialPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("commercial_plan_id");

                    b.Property<DateTime>("PerformedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by_user_id");

                    b.HasKey("ApprovalActionId");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("CommercialPlanId", "PerformedAt");

                    b.ToTable("approval_actions", null, t =>
                        {
                            t.HasCheckConstraint("CK_approval_actions_type", "action_type IN ('submitted','revisionrequested','approved','rejected')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.Buyer", b =>
                {
                    b.Property<Guid>("BuyerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("BuyerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("buyer_type");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("company_name");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact_person");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("BuyerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("buyers", null, t =>
                        {
                            t.HasCheckConstraint("CK_buyers_status", "status IN ('pending','active','suspended')");

                            t.HasCheckConstraint("CK_buyers_type", "buyer_type IN ('local','export')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.CommercialPlan", b =>
                {
                    b.Property<Guid>("CommercialPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("commercial_plan_id");

                    b.Property<bool>("ApprovalRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("approval_required");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DestinationCountry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("destination_country");

                    b.Property<decimal>("EstimatedCosts")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("estimated_costs");

                    b.Property<decimal>("EstimatedNetValue")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("estimated_net_value");

                    b.Property<decimal>("ExpectedRevenue")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("expected_revenue");

                    b.Property<string>("MaterialsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("materials_json");

                    b.Property<string>("ReasoningSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reasoning_summary");

                    b.Property<string>("RecommendedRoute")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("recommended_route");

                    b.Property<string>("RiskFlags")
                        .HasColumnType("jsonb")
                        .HasColumnName("risk_flags");

                    b.Property<Guid?>("SelectedBuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("selected_buyer_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("CommercialPlanId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SelectedBuyerId");

                    b.HasIndex("Status");

                    b.HasIndex("WorkflowId");

                    b.ToTable("commercial_plans", null, t =>
                        {
                            t.HasCheckConstraint("CK_commercial_plans_costs_non_negative", "estimated_costs >= 0");

                            t.HasCheckConstraint("CK_commercial_plans_revenue_non_negative", "expected_revenue >= 0");

                            t.HasCheckConstraint("CK_commercial_plans_route", "recommended_route IN ('localsale','export')");

                            t.HasCheckConstraint("CK_commercial_plans_status", "status IN ('draft','pendingapproval','approved','rejected','revisionrequested','executed')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.ExportOrder", b =>
                {
                    b.Property<Guid>("ExportOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("export_order_id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DestinationCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("destination_country");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("ShipmentDate")
                        .HasColumnType("date")
                        .HasColumnName("shipment_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalValue")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_value");

                    b.Property<decimal>("TotalWeightKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_weight_kg");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ExportOrderId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DestinationCountry");

                    b.HasIndex("Status", "OrderDate");

                    b.ToTable("export_orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_export_orders_status", "status IN ('draft','pendingapproval','approved','shipped','completed','cancelled')");

                            t.HasCheckConstraint("CK_export_orders_value_non_negative", "total_value >= 0");

                            t.HasCheckConstraint("CK_export_orders_weight_non_negative", "total_weight_kg >= 0");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.ExportOrderItem", b =>
                {
                    b.Property<Guid>("ExportOrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("export_order_item_id");

                    b.Property<Guid>("ExportOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("export_order_id");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("line_total");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material_type");

                    b.Property<decimal>("QuantityKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("quantity_kg");

                    b.Property<Guid>("RecoveredMaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("recovered_material_id");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("ExportOrderItemId");

                    b.HasIndex("ExportOrderId");

                    b.HasIndex("RecoveredMaterialId");

                    b.ToTable("export_order_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_export_order_items_price", "unit_price >= 0");

                            t.HasCheckConstraint("CK_export_order_items_qty", "quantity_kg > 0");

                            t.HasCheckConstraint("CK_export_order_items_total", "line_total >= 0");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.MaterialPricing", b =>
                {
                    b.Property<Guid>("PricingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("pricing_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material_type");

                    b.Property<decimal>("PricePerKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price_per_kg");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PricingId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("MaterialType", "EffectiveDate")
                        .IsUnique();

                    b.HasIndex("MaterialType", "Status");

                    b.ToTable("material_pricing", null, t =>
                        {
                            t.HasCheckConstraint("CK_material_pricing_dates", "expiry_date IS NULL OR expiry_date > effective_date");

                            t.HasCheckConstraint("CK_material_pricing_price_positive", "price_per_kg > 0");

                            t.HasCheckConstraint("CK_material_pricing_status", "status IN ('draft','approved','expired')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.RevenueTransaction", b =>
                {
                    b.Property<Guid>("RevenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("revenue_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remarks");

                    b.Property<DateTime>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("transaction_type");

                    b.HasKey("RevenueId");

                    b.HasIndex("RecordedByUserId");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("TransactionType", "ReferenceId")
                        .IsUnique();

                    b.ToTable("revenue_transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_revenue_transactions_amount_positive", "amount > 0");

                            t.HasCheckConstraint("CK_revenue_transactions_type", "transaction_type IN ('localsale','export')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.SalesOrder", b =>
                {
                    b.Property<Guid>("SalesOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("sales_order_id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SalesOrderId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Status", "OrderDate");

                    b.ToTable("sales_orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_sales_orders_status", "status IN ('draft','confirmed','completed','cancelled')");

                            t.HasCheckConstraint("CK_sales_orders_total_non_negative", "total_amount >= 0");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.SalesOrderItem", b =>
                {
                    b.Property<Guid>("SalesOrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("sales_order_item_id");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("line_total");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material_type");

                    b.Property<decimal>("QuantityKg")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("quantity_kg");

                    b.Property<Guid>("RecoveredMaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("recovered_material_id");

                    b.Property<Guid>("SalesOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_order_id");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("SalesOrderItemId");

                    b.HasIndex("RecoveredMaterialId");

                    b.HasIndex("SalesOrderId");

                    b.ToTable("sales_order_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_sales_order_items_price_non_negative", "unit_price >= 0");

                            t.HasCheckConstraint("CK_sales_order_items_quantity_positive", "quantity_kg > 0");

                            t.HasCheckConstraint("CK_sales_order_items_total_non_negative", "line_total >= 0");
                        });
                });

            modelBuilder.Entity("EWasteManagement.Api.Entities.AIAnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedValueUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EstimatedVolumeKg")
                        .HasColumnType("numeric");

                    b.Property<string>("HazardLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiresHumanApproval")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("WasteCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.ToTable("AIAnalysisResults");
                });

            modelBuilder.Entity("EWasteManagement.Api.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("EWasteManagement.Api.Entities.SubmissionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("SubmissionItems");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.ApprovalAction", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Sales.Entities.CommercialPlan", "CommercialPlan")
                        .WithMany("ApprovalActions")
                        .HasForeignKey("CommercialPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EWasteManagement.API.Features.Auth.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CommercialPlan");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.Buyer", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Auth.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("EWasteManagement.API.Features.Sales.Entities.Buyer", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.CommercialPlan", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Sales.Entities.Buyer", "SelectedBuyer")
                        .WithMany()
                        .HasForeignKey("SelectedBuyerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SelectedBuyer");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.ExportOrder", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Sales.Entities.Buyer", "Buyer")
                        .WithMany("ExportOrders")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EWasteManagement.API.Features.Auth.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.ExportOrderItem", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Sales.Entities.ExportOrder", "ExportOrder")
                        .WithMany("Items")
                        .HasForeignKey("ExportOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExportOrder");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.MaterialPricing", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Auth.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.RevenueTransaction", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Auth.Entities.User", "RecordedByUser")
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RecordedByUser");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.SalesOrder", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Sales.Entities.Buyer", "Buyer")
                        .WithMany("SalesOrders")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EWasteManagement.API.Features.Auth.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.SalesOrderItem", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Sales.Entities.SalesOrder", "SalesOrder")
                        .WithMany("Items")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("EWasteManagement.Api.Entities.AIAnalysisResult", b =>
                {
                    b.HasOne("EWasteManagement.Api.Entities.Submission", null)
                        .WithOne("AIAnalysis")
                        .HasForeignKey("EWasteManagement.Api.Entities.AIAnalysisResult", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EWasteManagement.Api.Entities.SubmissionItem", b =>
                {
                    b.HasOne("EWasteManagement.Api.Entities.Submission", null)
                        .WithMany("Items")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.Buyer", b =>
                {
                    b.Navigation("ExportOrders");

                    b.Navigation("SalesOrders");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.CommercialPlan", b =>
                {
                    b.Navigation("ApprovalActions");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.ExportOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Sales.Entities.SalesOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EWasteManagement.Api.Entities.Submission", b =>
                {
                    b.Navigation("AIAnalysis");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
