// <auto-generated />
using System;
using EWasteManagement.API.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EWasteManagement.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EWasteManagement.API.Features.Auth.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("CK_users_role", "role IN ('household','corporate','collector','staff','admin')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Collection.Entities.Collector", b =>
                {
                    b.Property<Guid>("CollectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("collector_id");

                    b.Property<decimal>("CapacityKg")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("capacity_kg");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("CurrentLatitude")
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("current_latitude");

                    b.Property<decimal?>("CurrentLongitude")
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("current_longitude");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_available");

                    b.Property<DateTime?>("LocationUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("location_updated_at");

                    b.Property<decimal>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(5.0m)
                        .HasColumnName("rating");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vehicle_type");

                    b.HasKey("CollectorId");

                    b.HasIndex("IsAvailable");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("collectors", (string)null);
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Collection.Entities.Job", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid?>("CollectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("collector_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("EstimatedDistanceKm")
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("estimated_distance_km");

                    b.Property<int?>("EstimatedEtaMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_eta_minutes");

                    b.Property<decimal?>("MeasuredWeightKg")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("measured_weight_kg");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pickup_address");

                    b.Property<decimal?>("PickupLatitude")
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("pickup_latitude");

                    b.Property<decimal?>("PickupLongitude")
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("pickup_longitude");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<DateTime?>("ScheduledWindowEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_window_end");

                    b.Property<DateTime?>("ScheduledWindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_window_start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.HasKey("JobId");

                    b.HasIndex("CollectorId");

                    b.HasIndex("Status");

                    b.HasIndex("SubmissionId");

                    b.ToTable("jobs", null, t =>
                        {
                            t.HasCheckConstraint("CK_jobs_status", "status IN ('assigned','accepted','rejected','inprogress','completed','cancelled','nocollectoravailable','pickuplocationunresolved')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Collection.Entities.JobAssignmentHistory", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("history_id");

                    b.Property<Guid>("CollectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("collector_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.HasKey("HistoryId");

                    b.HasIndex("CollectorId");

                    b.HasIndex("JobId");

                    b.HasIndex("JobId", "CollectorId");

                    b.ToTable("job_assignment_history", null, t =>
                        {
                            t.HasCheckConstraint("CK_job_assignment_history_outcome", "outcome IN ('assigned','accepted','rejected')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.ClassificationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<DateTime>("ClassifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("classified_at");

                    b.Property<Guid?>("ClassifiedByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("classified_by_staff_id");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(4,3)")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_final");

                    b.Property<Guid?>("OverriddenByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("overridden_by_staff_id");

                    b.Property<string>("OverrideReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("override_reason");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("source");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sub_category");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("classification_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_classification_records_category", "category IN ('reusable','localrecyclable','hazardous','exportonly')");

                            t.HasCheckConstraint("ck_classification_records_source", "source IN ('manual','ai')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.CollectorPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CollectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("collector_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SourceType", "SourceId")
                        .IsUnique();

                    b.ToTable("collector_payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_collector_payments_source_type", "source_type IN ('job','extrawaste')");

                            t.HasCheckConstraint("ck_collector_payments_status", "status IN ('pending','paid')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.ExtraWasteReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CollectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("collector_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid>("ReceivedByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("received_by_staff_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.ToTable("extra_waste_receipts", (string)null);
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.ExtraWasteReceiptItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Accepted")
                        .HasColumnType("boolean")
                        .HasColumnName("accepted");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExtraWasteReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("extra_waste_receipt_id");

                    b.Property<Guid?>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("item_type");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("weight_kg");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ExtraWasteReceiptId");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("extra_waste_receipt_items", (string)null);
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CurrentLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_location_id");

                    b.Property<Guid?>("ExtraWasteReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("extra_waste_receipt_id");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("item_type");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("OriginType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origin_type");

                    b.Property<Guid?>("ParentInventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_inventory_item_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<decimal>("VerifiedWeightKg")
                        .HasColumnType("decimal(10,3)")
                        .HasColumnName("verified_weight_kg");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CurrentLocationId");

                    b.HasIndex("ExtraWasteReceiptId");

                    b.HasIndex("JobId")
                        .IsUnique()
                        .HasFilter("job_id IS NOT NULL");

                    b.HasIndex("ParentInventoryItemId");

                    b.ToTable("inventory_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_items_origin_type", "origin_type IN ('jobcollection','extrawaste')");

                            t.HasCheckConstraint("ck_inventory_items_status", "status IN ('received','sorting','dismantling','classified','readyforsale','exportonly','onhold')");
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.ProcessingLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<Guid>("PerformedByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by_staff_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("processing_logs", (string)null);
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.RatePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("item_type");

                    b.Property<decimal>("RatePerKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("rate_per_kg");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ItemType")
                        .IsUnique()
                        .HasFilter("is_active = true");

                    b.ToTable("rate_policies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            CreatedAt = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveFrom = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ItemType = "Laptop",
                            RatePerKg = 50m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveFrom = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ItemType = "Mobile Phone",
                            RatePerKg = 80m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveFrom = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ItemType = "Battery",
                            RatePerKg = 30m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveFrom = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ItemType = "General Household Electronics",
                            RatePerKg = 40m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAt = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            EffectiveFrom = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ItemType = "GeneralCollection",
                            RatePerKg = 20m
                        });
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.WarehouseLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("warehouse_locations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            CreatedAt = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Where collector deliveries and extra-waste drop-offs are first received and weighed.",
                            Name = "Receiving Bay"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            CreatedAt = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Items are sorted by category before dismantling or direct classification.",
                            Name = "Sorting Area"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            CreatedAt = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Items are broken down into separately trackable child components.",
                            Name = "Dismantling Area"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            CreatedAt = new DateTime(2026, 9, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classified items awaiting handoff to Component D.",
                            Name = "Ready-for-Sale Storage"
                        });
                });

            modelBuilder.Entity("EWasteManagement.Api.Entities.AIAnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedValueUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EstimatedVolumeKg")
                        .HasColumnType("numeric");

                    b.Property<string>("HazardLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiresHumanApproval")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("WasteCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.ToTable("AIAnalysisResults");
                });

            modelBuilder.Entity("EWasteManagement.Api.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedWeight")
                        .HasColumnType("numeric");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("EWasteManagement.Api.Entities.SubmissionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("SubmissionItems");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Collection.Entities.Collector", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Auth.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Collection.Entities.Job", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Collection.Entities.Collector", "CollectorEntity")
                        .WithMany()
                        .HasForeignKey("CollectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CollectorEntity");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.ClassificationRecord", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Processing.Entities.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.ExtraWasteReceiptItem", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Processing.Entities.ExtraWasteReceipt", "ExtraWasteReceipt")
                        .WithMany("Items")
                        .HasForeignKey("ExtraWasteReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EWasteManagement.API.Features.Processing.Entities.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ExtraWasteReceipt");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.InventoryItem", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Processing.Entities.WarehouseLocation", "CurrentLocation")
                        .WithMany()
                        .HasForeignKey("CurrentLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EWasteManagement.API.Features.Processing.Entities.ExtraWasteReceipt", "ExtraWasteReceipt")
                        .WithMany()
                        .HasForeignKey("ExtraWasteReceiptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EWasteManagement.API.Features.Processing.Entities.InventoryItem", "ParentInventoryItem")
                        .WithMany()
                        .HasForeignKey("ParentInventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentLocation");

                    b.Navigation("ExtraWasteReceipt");

                    b.Navigation("ParentInventoryItem");
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.ProcessingLog", b =>
                {
                    b.HasOne("EWasteManagement.API.Features.Processing.Entities.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("EWasteManagement.Api.Entities.AIAnalysisResult", b =>
                {
                    b.HasOne("EWasteManagement.Api.Entities.Submission", null)
                        .WithOne("AIAnalysis")
                        .HasForeignKey("EWasteManagement.Api.Entities.AIAnalysisResult", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EWasteManagement.Api.Entities.SubmissionItem", b =>
                {
                    b.HasOne("EWasteManagement.Api.Entities.Submission", null)
                        .WithMany("Items")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EWasteManagement.API.Features.Processing.Entities.ExtraWasteReceipt", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EWasteManagement.Api.Entities.Submission", b =>
                {
                    b.Navigation("AIAnalysis");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
